// Generated by scripts/s2-t314-generate-founder-registry.mjs.
// Exact membership is the authority; do not replace this set with a pattern.
export const DICE_FOUNDER_FIXTURE_REGISTRY_VERSION = "dice_founder_fixture_registry_v1" as const;
export const DICE_FOUNDER_FIXTURE_REGISTRY_SHA256 = "a6f2700b5b689bc00a130bde083e2efbce1a83ac64df8ddaee5565b2f2e9d211" as const;

export const DICE_FOUNDER_FIXTURES = Object.freeze([
  { fixture_id: "dice-founder-en-01", authoring_id: "EN01", language: "en", exact_text: "How’s the condition in my current job like?" },
  { fixture_id: "dice-founder-en-02", authoring_id: "EN02", language: "en", exact_text: "Will I be promoted in the coming review?" },
  { fixture_id: "dice-founder-en-03", authoring_id: "EN03", language: "en", exact_text: "If I change my job, how soon will I be able to get a new job?" },
  { fixture_id: "dice-founder-en-04", authoring_id: "EN04", language: "en", exact_text: "What should I do next weekend?" },
  { fixture_id: "dice-founder-en-05", authoring_id: "EN05", language: "en", exact_text: "Shall I bring my dog to this new vet?" },
  { fixture_id: "dice-founder-en-06", authoring_id: "EN06", language: "en", exact_text: "Why is the relationship between me and my girlfriend not good?" },
  { fixture_id: "dice-founder-en-07", authoring_id: "EN07", language: "en", exact_text: "Does my boyfriend have an affair?" },
  { fixture_id: "dice-founder-en-08", authoring_id: "EN08", language: "en", exact_text: "How can me and my girlfriend improve our relationship?" },
  { fixture_id: "dice-founder-en-09", authoring_id: "EN09", language: "en", exact_text: "Will we get married? If so, when?" },
  { fixture_id: "dice-founder-en-10", authoring_id: "EN10", language: "en", exact_text: "How did my interview go?" },
  { fixture_id: "dice-founder-en-11", authoring_id: "EN11", language: "en", exact_text: "Where can I find my next love?" },
  { fixture_id: "dice-founder-en-12", authoring_id: "EN12", language: "en", exact_text: "What should I be aware of in my next trip to Japan?" },
  { fixture_id: "dice-founder-en-13", authoring_id: "EN13", language: "en", exact_text: "Why did I not get the promotion?" },
  { fixture_id: "dice-founder-en-14", authoring_id: "EN14", language: "en", exact_text: "I am looking to do a side business, what should I do?" },
  { fixture_id: "dice-founder-en-15", authoring_id: "EN15", language: "en", exact_text: "Where can I find my pair of glasses?" },
  { fixture_id: "dice-founder-en-16", authoring_id: "EN16", language: "en", exact_text: "I am looking to start some new courses, what should I apply for?" },
  { fixture_id: "dice-founder-en-17", authoring_id: "EN17", language: "en", exact_text: "When will I be pregnant?" },
  { fixture_id: "dice-founder-en-18", authoring_id: "EN18", language: "en", exact_text: "Is this doctor reliable?" },
  { fixture_id: "dice-founder-en-19", authoring_id: "EN19", language: "en", exact_text: "How well will the exhibition go next week?" },
  { fixture_id: "dice-founder-en-20", authoring_id: "EN20", language: "en", exact_text: "What type of people is my next manager?" },
  { fixture_id: "dice-founder-zh-01", authoring_id: "ZH01", language: "zh-Hant", exact_text: "我應唔應該去Working holiday？" },
  { fixture_id: "dice-founder-zh-02", authoring_id: "ZH02", language: "zh-Hant", exact_text: "Working holiday去澳洲好唔好？" },
  { fixture_id: "dice-founder-zh-03", authoring_id: "ZH03", language: "zh-Hant", exact_text: "Working holiday去美國好唔好？" },
  { fixture_id: "dice-founder-zh-04", authoring_id: "ZH05", language: "zh-Hant", exact_text: "我去到澳洲如果讀書嘅，應該讀乜嘢？" },
  { fixture_id: "dice-founder-zh-05", authoring_id: "ZH06", language: "zh-Hant", exact_text: "我去到澳洲做嘢嘅話，係咪應該做返我而家呢行？" },
  { fixture_id: "dice-founder-zh-06", authoring_id: "ZH07", language: "zh-Hant", exact_text: "我去到澳洲應該有乜嘢需要注意？" },
  { fixture_id: "dice-founder-zh-07", authoring_id: "ZH08", language: "zh-Hant", exact_text: "我個application 會唔會批？幾時會批？" },
  { fixture_id: "dice-founder-zh-08", authoring_id: "ZH09", language: "zh-Hant", exact_text: "我個application幾時會批？" },
  { fixture_id: "dice-founder-zh-09", authoring_id: "ZH10", language: "zh-Hant", exact_text: "我同個男朋友應唔應該繼續呢段關係？" },
  { fixture_id: "dice-founder-zh-10", authoring_id: "ZH11", language: "zh-Hant", exact_text: "我同我男朋友究竟而家發生咩問題？" },
  { fixture_id: "dice-founder-zh-11", authoring_id: "ZH12", language: "zh-Hant", exact_text: "我如果搬去佢屋企附近會唔會改善到我哋嘅關係？" },
  { fixture_id: "dice-founder-zh-12", authoring_id: "ZH13", language: "zh-Hant", exact_text: "我可以做乜嘢去改善我哋嘅關係？" },
  { fixture_id: "dice-founder-zh-13", authoring_id: "ZH14", language: "zh-Hant", exact_text: "我九月嘅運程係點？" },
  { fixture_id: "dice-founder-zh-14", authoring_id: "ZH15", language: "zh-Hant", exact_text: "如果我讀呢個占星course會點？" },
  { fixture_id: "dice-founder-zh-15", authoring_id: "ZH16", language: "zh-Hant", exact_text: "我下個星期去台灣擺展覽，個情況會係點？" },
  { fixture_id: "dice-founder-zh-16", authoring_id: "ZH17", language: "zh-Hant", exact_text: "我應該做乜嘢副業會賺多啲錢？" },
  { fixture_id: "dice-founder-zh-17", authoring_id: "ZH18", language: "zh-Hant", exact_text: "我嚟緊有個空降嘅上司，佢係一個咩人？" },
  { fixture_id: "dice-founder-zh-18", authoring_id: "ZH19", language: "zh-Hant", exact_text: "我今個月月會唔會到數？" },
  { fixture_id: "dice-founder-zh-19", authoring_id: "ZH20", language: "zh-Hant", exact_text: "我點樣先至可以到數？" },
  { fixture_id: "dice-founder-zh-20", authoring_id: "ZH21", language: "zh-Hant", exact_text: "我幾時先至可以搵到份新工？" },
] as const);

const DICE_FOUNDER_FIXTURES_BY_ID: ReadonlyMap<string, (typeof DICE_FOUNDER_FIXTURES)[number]> = new Map(DICE_FOUNDER_FIXTURES.map((fixture) => [fixture.fixture_id, fixture]));
const DICE_FOUNDER_FIXTURES_BY_AUTHORING_ID: ReadonlyMap<string, (typeof DICE_FOUNDER_FIXTURES)[number]> = new Map(DICE_FOUNDER_FIXTURES.map((fixture) => [fixture.authoring_id, fixture]));
const DICE_FOUNDER_FIXTURES_BY_EXACT_TEXT: ReadonlyMap<string, (typeof DICE_FOUNDER_FIXTURES)[number]> = new Map(DICE_FOUNDER_FIXTURES.map((fixture) => [fixture.exact_text, fixture]));

export type ApprovedDiceFounderFixtureId = (typeof DICE_FOUNDER_FIXTURES)[number]["fixture_id"];

export function isApprovedDiceFounderFixtureId(value: unknown): value is ApprovedDiceFounderFixtureId {
  return typeof value === "string" && DICE_FOUNDER_FIXTURES_BY_ID.has(value);
}

export function resolveDiceFounderFixture(fixtureId: string) {
  return DICE_FOUNDER_FIXTURES_BY_ID.get(fixtureId) ?? null;
}

export function resolveDiceFounderFixtureByAuthoringId(authoringId: string) {
  return DICE_FOUNDER_FIXTURES_BY_AUTHORING_ID.get(authoringId) ?? null;
}

export function resolveDiceFounderFixtureByExactText(exactText: string) {
  return DICE_FOUNDER_FIXTURES_BY_EXACT_TEXT.get(exactText) ?? null;
}
