declare const process: {
  env: {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_KEY?: string;
    EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_DICE_RITUAL?: string;
    EXPO_PUBLIC_PERSONA_COMPARISON_WORKBENCH?: string;
    EXPO_PUBLIC_CARE_CIRCLE_STAGING_WORKBENCH?: string;
    EXPO_PUBLIC_CARE_CIRCLE_STAGING_DEPLOYMENT_READY?: string;
    EXPO_PUBLIC_SUPABASE_PROJECT_REF?: string;
  };
};
